import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import ContenProducto from '@/components/ContenProducto';
import Productos from '@/components/Cards';
import data from '../data/bebida.json';
import RandomCards from '@/components/RandomCards';
import React from 'react';
import { useTranslation } from 'react-i18next';
//import data from '../translations/en/bebida.json';
//import data from '../translations/es/bebida.json';

export default function Home() {
  /* ===== traductor ===== */
  const [ t, i18n ] = useTranslation ("traduccion");

  return (
    <>
    <div>
      <Head>
        <title>{t("navbar.bebida")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/P.png" />
      </Head>
      <main>
  
      <body>
        <br></br>
        <br></br>
        <br></br>
        <ContenProducto>

          {data.map( bebida =>
          <Productos
            id={bebida.id}
            titulo = {bebida.titulo}
            precio = {bebida.precio}
            imagen = {bebida.imagen}
            texto = {bebida.texto}
                   
          />
            
            )}
            <br></br>
            <br></br>
            
        </ContenProducto>
        <br></br>     
      </body>
        <RandomCards/>
      </main>
      </div>
    
      </>

  )
}
