import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import Barra from '@/components/Navbar';
import ContenProducto from '@/components/ContenProducto';
import Productos from '@/components/Cards';
import data from '../data/comida.json';
import RandomCards from '@/components/RandomCards';
import React from 'react';
import { useTranslation } from 'react-i18next';

export default function Home() {
  /* ===== traductor ===== */
  const [ t, i18n ] = useTranslation ("traduccion");
  
  return (
    <>
    <div >
      <Head>
        <title>{t("navbar.comida")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/P.png" />
      </Head>
      <main>
        <Barra />
      
      <body>
               
        <br></br>
        <br></br>
        <br></br>
        <ContenProducto>

          {data.map( comida =>
          <Productos
            id={comida.id}
            titulo = {comida.titulo}
            precio = {comida.precio}
            imagen = {comida.imagen}
            texto = {comida.texto}/>
            
            )}
            <br></br>
            <br></br>
            
        </ContenProducto>
      </body>      
        <RandomCards />  
      </main>     
      </div>
    
      </>

  )
}
