import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import useScrollTop from '@/components/hooks/useScrollTop';
import BarraNav from '@/components/navbar/navbar';
import { Button, Form } from 'react-bootstrap';
 
export default function Home() {
  useScrollTop();
  return (
    <div style={{ backgroundImage: "url(/background.png)", backgroundRepeat: 'no-repeat'}}>
      <Head>
        <title>Pedilo Ya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/P.png" />
      </Head>

      <main className={`${styles.main}`}>
      <BarraNav />

    <div className="titulos">
      <h1>¡Pedí lo que quieras!
        </h1>
      <p>Restaurantes, mercados, farmacias, kioscos y muchos más.</p>
      <Form className="d-flex">
            <Form.Control
              type="search"
              placeholder="Search"
              className="me-2"
              aria-label="Search"
            />
            <Button variant="outline-warning">Search</Button>
          </Form>
      </div>
      
      </main>
    </div>
  )
}
