import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Button, Form } from 'react-bootstrap';
import Barra from '@/components/nav';
import Carousel from '@/components/Carousel';
import Footer from '@/components/Footer';
import Searchbar from '@/components/searchbar';


export default function Home() {

  return (
    <div style={{ backgroundImage: "url(/background.png)", backgroundRepeat: 'no-repeat'}}>
      <Head>
        <title>Pedilo Ya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/P.png" />
      </Head>

      <main className={`${styles.main}`}>
      <Barra />

        <div className="titulos">
          <h1>¡Pedí lo que quieras!
          </h1>
          <p>Restaurantes, mercados, farmacias, kioscos y muchos más.</p>
          <Form className="d-flex">
          <Searchbar></Searchbar>
           
          </Form>
        </div>
      </main>
      <body>
        <Carousel />
      </body>
      <div>
        <Footer />
      </div>
    </div>
  )
}
