import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head';
import Productos from '@/components/Cards';
import data from '../data/postres.json';
import ContenProducto from '@/components/ContenProducto';
import RandomCards from '@/components/RandomCards';
import React from 'react';
import { useTranslation } from 'react-i18next';


export default function Home() {
  /* ===== traductor ===== */
  const [ t, i18n ] = useTranslation ("traduccion");

  return (
    <>
      <div>
        <Head>
          <title>{t("navbar.postre")}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/P.png" />
        </Head>
        <main>
       
        <body>
          <br></br>
          <br></br>
          <br></br>
          <ContenProducto>

            {data.map(postres =>
              <Productos
                id={postres.id}
                titulo={postres.titulo}
                precio={postres.precio}
                imagen={postres.imagen}
                texto={postres.texto}

              />
            )}
            <br></br>
            <br></br>
          </ContenProducto>
          <br></br>
        </body>
          <RandomCards/>
        </main>

      </div>

    </>

  )
}

